all:cp

cp:
	cp -rf *.lua $(HOME)/lib/lua/
	cp -rf unittest/*.lua $(HOME)/lib/lua/
	cp -rf collections $(HOME)/lib/lua/
	cp -rf glr $(HOME)/lib/lua/
	cp -rf native ${HOME}/lib/lua/
	cp -rf http $(HOME)/lib/lua/
	cp -rf os $(HOME)/lib/lua/
