#! /usr/bin/env bash

while true
do
    mem_usage=`awk 'BEGIN { MemTotal=0; MemFree=0; }
    /MemTotal/{MemTotal=$2};
    /MemFree/{MemFree=$2}; 
    END{ 
    printf("%.2f\n",100 - 100* MemFree/MemTotal);}' /proc/meminfo`

    echo $mem_usage
    sleep 1
done
