#! /usr/bin/env bash

lines=$1
total_line=`cat monitor_data/cpu_monitor| wc -l`
lines=${lines:=$total_line}
for i in `seq $lines`
do
    cpu_line=`awk -v line=$i '{ if(NR==line){ print $0} }' monitor_data/cpu_monitor`
    mem_line=`awk -v line=$i '{ if(NR==2){ print $0} }' monitor_data/mem_monitor`
    io_line=`awk -v line=$i '{ if(NR==2){ print $0} }' monitor_data/io_monitor`
    network_line=`awk -v line=$i '{ if(NR==2){ print $0} }' monitor_data/network_monitor`
    echo $cpu_line $mem_line $io_line $network_line
done

