#! /usr/bin/env bash

mkdir -p monitor_data
(./io-throughput >> monitor_data/io_monitor)&
(./network-throughput eth0 >> monitor_data/network_monitor)&
(./cpu-usage >> monitor_data/cpu_monitor)&
(./mem-usage >> monitor_data/mem_monitor)&
