
all: etree luaiconv luaxpath

etree:
	make -C etree-0.1.1

luaiconv:
	make -C lua-iconv-7

luaxpath:
	make -C luaxpath

.PHONY: clean
	make -C etree-0.1.1 clean
	make -C lua-iconv-7 clean
	make -C luaxpath clean
