#! /bin/sh

for i in `ls timer/timer_*`; do cat $i >> timer/timer_tmp; done
cat timer/timer_tmp | sort -t " " -k 6 >> timer/timer

echo "实际请求数: `cat timer/timer | grep "processID" | wc -l `"
echo "总失败数:`cat timer/timer | grep "ret:false" | wc -l `"
echo "glr.recLine() timeout : `cat timer/timer | grep "initLine timeout" | wc -l `" 
echo "glr.recv() timeout: `cat timer/timer | grep "recv timeout" | wc -l `"
echo "Sokcet Send timeout: `cat timer/timer | grep "SendWait timeou" | wc -l`" 

#mv --backup=t timer/ /tmp/

#echo "----- tps------"
#cat tps/tps
#mv --backup=t tps/ /tmp/
